CREATE TABLE cam(
id SERIAL PRIMARY KEY,
nameCam VARCHAR(255) NOT NULL,
location VARCHAR(255) NOT NULL,
latitude DECIMAL(10, 8) NOT NULL,
longitude DECIMAL(11, 8) NOT NULL,
camId VARCHAR(255) NOT NULL
);